# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				arrow = true
				cow = true
				pig = true
				allay = true
				skeleton = true
				bat = true
				husk = true
				frog = true
				rabbit = true
				firework_rocket = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				vex = true
				goat = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				donkey = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				slime = true
				iron_golem = true
				cat = true
				zombie = true
				sheep = true
				player = true
				wolf = true
				villager = true
				zombie_villager = true
				tnt_minecart = true
				small_fireball = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.spell_engine]
				spell_area_effect = true

			[light_sources.settings.entities.spellbladenext]
				magister = true
				cycloneentity = true
				hexbladeportal = true
				magus = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.arcanuscontinuum]
				opossum = true
				wizard = true

			[light_sources.settings.entities.lostrelics]
				doppelganger = true

			[light_sources.settings.entities.supplementaries]
				red_merchant = true

			[light_sources.settings.entities.aylyth]
				elder_aylythian = true
				aylythian = true
				wreathed_hind = true
				ripped_soul = true
				faunaylythian = true
				scion = true
				pilot_light = true

