name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d20ea619999f85b2992669bc0f25890bcf80aaafe9b406fdd7c80dd89c57ef"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
