name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.0.39"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "195a2cec2279867a23371feb83e103197326637c2a72e79de4797be3d762b7de"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
