# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				husk = true
				bat = true
				frog = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				item = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				goat = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				evoker = true
				glow_squid = true
				warden = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				donkey = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				cat = true
				zombie = true
				guardian = true
				sheep = true
				player = true
				pufferfish = true
				illusioner = true
				potion = true
				villager = true
				wolf = true
				zombie_villager = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true

			[light_sources.settings.entities.fallingtrees]
				tree = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				rhino = true
				snake = true
				catfish = true
				robin = true
				boar = true
				duck_egg = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				zebra = true
				rattlesnake = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				elephant = true
				finch = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				tank = true

			[light_sources.settings.entities.uselessreptile]
				moleclaw = true
				wyvern_projectile = true
				river_pikehorn = true
				wyvern = true

			[light_sources.settings.entities.xercapaint]
				easel = true

			[light_sources.settings.entities.enderzoology]
				fallen_mount = true
				owl = true
				wither_witch = true
				wither_cat = true
				owl_egg = true
				fallen_knight = true
				infested_zombie = true
				enderminy = true
				concussion_creeper = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.arcanuscontinuum]
				opossum = true
				wizard = true

			[light_sources.settings.entities.mythicmobs]
				mushroom_thing = true

			[light_sources.settings.entities.illagerinvasion]
				sorcerer = true
				archivist = true
				provoker = true
				basher = true

